Rk/add footer
rkaufman13/Noodle pull request #15
Opened 2023-07-25 01:45 UTC by rkaufman13

Small one-- adds a footer to every page and an about page.

2023-07-25 02:44 UTC, eggchan requested changes
A few suggestions and a few syntax fix requests

2023-07-25 02:44 UTC, eggchan commented on src/App.js
> +      <Container className="footer">
This should live inside of a `<footer>` tag. Ideally remove the footer class. And there needs to be a `<Col xl={8}` inside the row and then call the Footer

2023-07-25 02:44 UTC, eggchan commented on src/About.jsx
A suggestion of how this should be laid out:
```
<Container>
 <Row>
  <Col>
   <h2>About Noodle</h2>
    <p>Scheduling events <em>used</em> to be easy on the other sites. Then they started to suck. Intrusive ads, pop-ups, forced logins, slow-loading pages, all that jazz.</p>
    <p>Noodle is a new take on event scheduling. No ads, no logins, no emails you don't want.</p>
    <p>Noodle was made by <a href="https://github.com/rkaufman13">Rachel Kaufman</a>, with lots of help from <a href="#">Sarah Tonsager</a> and <a href="https://chriscombs.net">Chris Combs</a>.</p>
   </Col>
  </Row>
</Container>
```

2023-07-25 02:44 UTC, eggchan commented on src/Footer.jsx
We should consider how this is going to look on a mobile device, e.g. it should stack once it gets to Bootstrap size sm.

2023-07-28 00:12 UTC, rkaufman13 commented on src/Footer.jsx
it actually looks OK on the device simulator...the margins of the main container, on the other hand, are not great, but that's a different issue.
![Screen Shot 2023-07-27 at 8 11 59 PM](https://github.com/rkaufman13/Noodle/assets/16939591/88bd6f60-a70c-4d8b-9180-78b935e1b1b9)

2023-07-28 00:20 UTC, eggchan commented on src/Footer.jsx
imo it should still stack but if you don't want it to I'm fine with leaving as is 🙂

2023-07-28 17:19 UTC, eggchan approved these changes

2023-07-29 13:14 UTC, merged