Rk/move email functions to backend
rkaufman13/Noodle pull request #21
Opened 2023-08-01 12:51 UTC by rkaufman13

The BULK of this PR involves removing the AWS logic from the frontend and calling a server instead.
Please note that going forward, if you do no additional setup, you will get console errors when triggering an action that sends an email (such as creating an event with an email address provided). These can safely be ignored. However, to get rid of them and test the end to end flow entirely, you will need to clone the `noodle-backend` repo, run it, set the `REACT_APP_BACKEND_BASE_URL` to localhost:3001, and add localhost:3001 as an allowed host in the CORS allowlist.
Or you can just get the console errors. :)

Also in this PR, because I'm a mess:
-Deleting a lot of the `default` bits in custom.scss, and adding the logic that creates utility classes for our colors
-Replacing unneeded `row`s with `div`s on the Admin page
-Adding Headings on the alerts
-A ton of Prettier stuff that doesn't seem to matter (replacing single quotes with double, etc).

2023-08-02 17:10 UTC, eggchan requested changes

2023-08-02 17:10 UTC, eggchan commented on src/aws_helpers/index.js
> +  console.log(JSON.stringify(params));
We've got a rogue console log, captain.

2023-08-02 17:10 UTC, eggchan commented on src/About.jsx
> +        <Col>
I believe the `<Container>`, `<Row>`, and `<Col>` that this is inside lives in the App.js file, so you shouldn't need these tags.

2023-08-02 17:10 UTC, eggchan commented on scss/custom.scss
This is going to be fun for me to merge with the branch I'm working on haha

2023-08-04 12:19 UTC, rkaufman13 commented
So AWS's trust and safety team has denied my request to use them in prod, so I have to close this entire PR and start over

2023-08-04 12:19 UTC, closed without merging